service: peter-park
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: 'eu-central-1'

custom:
  pythonRequirements:
    zip: true

package:
  patterns:
    - '! node_modules/**'   # exclude files from ./node_modules/**/*
    - requirement.zip
    - '!.venv/**'
    - '!.vscode/**'
    - '!.serverless/**'


functions:
  image_handler:
    handler: src/handler.image_handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements
